### ISSUE TITLE
Battery / Thinkpad x230

### ISSUE THREAD

**Issue by oxodao** [oxodao/metaprint#1]
Battery setup correctly not showing up on my Thinkpad for some reasons

```
battery:
  i3:
    battery_name: BAT0
    format: "%status_text% %percentage%%"
    charging_text: 🔌
    discharging_text: 🔋
    prefix: "  "
```
```
  ~/.config » metaprint battery i3
   -
```
```
  ~/.config » cat /sys/class/power_supply/BAT0/status
Discharging
```
